### ISSUE TITLE
Making a repo name with `-`, e.g. `my-repo` causes problems

### ISSUE THREAD

**Issue by mstefferson** [manifoldai/orbyter-cookiecutter#14]
Python modules cannot have dashes `-` in their name. It is recommended to use underscores `_`. However, I bunch of paths and made with dashes in the names. A user has to manually edit these.

**Comment by resdntalien** [comment]
@mstefferson Agreed -- how should we fix this? Can we restrict the repo name to not have '-' and do a check in the cookiecutter?

**Comment by mstefferson** [comment]
The issue is that people love putting dashes in there repo name (see this repo name for proof). We could probably parse the str, change the value, and use the new name. Maybe jijna can handle this? I'd have to check.
