### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by rameshvs** [manifoldai/orbyter-cookiecutter#84]
There are a few broken links in the README:

1. https://cookiecutter.readthedocs.io/en/latest/readme.html
2. https://medium.com/manifold-ai/torus-a-toolkit-for-docker-first-data-science-bddcb4c97b52

The README could probably also use a few adjustments to come up-to-date.

**Comment by JayThibs** [comment]
The img links to the mflow images are broken too. And a few more besides links too. They are pointing to docs/imgs, but the images are now in docsrc/imgs/.

**Comment by JayThibs** [comment]
@rameshvs Updated the links here:

https://github.com/manifoldai/orbyter-cookiecutter/pull/88

**Comment by jeffmm** [comment]
Addressed by @JayThibs in his PR
